name: Deploy

on: 
  push:
    branches:   
      - main
env:
  MAIN_DIRECTORY: "/var/www/html/1"
  PATH_TARGET: "/var/www/html/1_github"
  SITE: "http://space3.space"
 


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST_FF_RU }}
        USERNAME: ${{ secrets.USERNAME_FF_RU }}
        PORT: ${{ secrets.PORT_FF_RU }}
        PASSWORD: ${{ secrets.PASSWORD_FF_RU }}
      with:
        source: "."
        target: ${{ env.PATH_TARGET }}
        rm: "true"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_FF_RU }}
        USERNAME: ${{ secrets.USERNAME_FF_RU }}
        PORT: ${{ secrets.PORT_FF_RU }}
        PASSWORD: ${{ secrets.PASSWORD_FF_RU }}   
        script: |
          sudo mv ${{ env.MAIN_DIRECTORY }} ${{ env.MAIN_DIRECTORY }}_old && \
          sudo mv ${{ env.PATH_TARGET }} ${{ env.MAIN_DIRECTORY }} && \                        
          sudo rm -R ${{ env.MAIN_DIRECTORY }}_old 
