name: Deploy

on: 
  push:
    branches:
      - main
env:
  TEST : "Alex"



jobs:
  build:

    runs-on: ubuntu-latest
    outputs:
      exist: ${{ steps.checkfolder.outputs.test }}     

    steps:
    - name: Executing remote command
      id: checkfolder
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        PASSWORD: ${{ secrets.PASSWORD }}  
        envs: TEST
        script: |
         cd /var/www && \
         sudo ls -l && \
         echo "I am $Test"
    
    - name: After checking 2
      run: |
       echo ${{steps.checkfolder.outputs.exist}}
      
    - name: Create output 
      id: step1
      run: echo "::set-output name=test::hello"
      
    
    - name: Create output 2
      run: echo hoge
      if: (  ${{ steps.step1.outputs.test }} == 'hello' )
      
