name: Deploy

on: 
  push:
    branches:
      - main
env:
  TEST : "test"



jobs:
  build:

    runs-on: ubuntu-latest
    outputs:
      exist: ${{ steps.checkfolder.outputs.test }}     

    steps:
    - name: Executing remote command
      id: checkfolder
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        PASSWORD: ${{ secrets.PASSWORD }}  
        script: |
         cd /var/www && \
         sudo ls -l && \
         test -d "html" && echo "::set-output name=test::true" || echo "::set-output name=test:false"
    
    - name: After checking 2
      run: echo ${{steps.checkfolder.outputs.exist}}
      
    
    - name: After checking
      run: echo hoge
      if: ( steps.checkfolder.outputs.exist == 'true' )
      
